version: 1.0
os: linux
files:
  - source: /
    destination: /app/student-performance
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 180
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 180
      runas: root
